[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/history-search-multi-word"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/history-search-multi-word/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
 [".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
 [".oh-my-zsh/custom/plugins/colorize"]
    type = "archive"
    url = "https://github.com/zpm-zsh/colorize/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
 [".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
 [".oh-my-zsh/custom/plugins/you-should-use"]
    type = "archive"
    url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
 [".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    refreshPeriod = "168h"
[".hammerspoon/stackline/"]
    type = "archive"
    url = "https://github.com/AdamWagner/stackline/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/mc/skins/gruvbox256.ini"]
    type = "file"
#    url = "https://raw.githubusercontent.com/DmitriyMaksimovich/MidnightCommander-grovbox-port/master/gruvbox256.ini"
    url = "https://raw.githubusercontent.com/gruvbox-community/gruvbox-contrib/master/midnightcommander/gruvbox256.ini"
    refreshPeriod = "168h"
